# Generated by Django 3.2 on 2022-06-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_course_courseteacher_lesson'),
    ]

    operations = [
    ]
